version: '3.8'

services:

  mysql:
    restart: always
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nexus:
    restart: always
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
      
  sonarqube:
    restart: always
    image: sonarqube:latest
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-logs:/opt/sonarqube/logs
      - sonar-extensions:/opt/sonarqube/extensions

  springboot:
    restart: always
    image: naceradhoum/naceradhoum-bugbusters-4twin4-foyer
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  prometheus:
    restart: always
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    restart: always
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"

volumes:
  mysql_data:
  nexus-data:
  sonar-data:
  sonar-logs:
  sonar-extensions:
  grafana-storage:
