sonar.projectKey=devops
sonar.projectName=4TWIN4-BugBusters-Foyer
sonar.projectVersion=1.0

# sources et tests
sonar.sources=foyer/src/main/java
sonar.tests=foyer/src/test/java

# classes compilées
sonar.java.binaries=foyer/target/classes
sonar.java.test.binaries=foyer/target/test-classes

# exclusions éventuelles
sonar.exclusions=**/foyer/target/**/*.jar
